'use client'

import { useMemo, useState } from 'react'
import {
  Bell, CalendarDays, ChevronDown, CircleHelp, ClipboardList, Clock3,
  Command, FileText, Flag, LayoutDashboard, LogOut, Menu, Search, Settings,
  ShieldCheck, SlidersHorizontal, Trophy, UserRound, Users, X, Zap,
} from 'lucide-react'

const matches = [
  { time: '09:30', home: 'HC Rotterdam', away: 'Kampong', homeScore: '3', awayScore: '2', status: 'Live', field: 'Field 1', accent: 'amber' },
  { time: '11:15', home: 'Den Bosch', away: 'Bloemendaal', homeScore: '—', awayScore: '—', status: 'Upcoming', field: 'Field 2', accent: 'blue' },
  { time: '13:00', home: 'Pinoké', away: 'Amsterdam', homeScore: '—', awayScore: '—', status: 'Upcoming', field: 'Field 1', accent: 'violet' },
  { time: '15:30', home: 'HGC', away: 'Oranje-Rood', homeScore: '1', awayScore: '1', status: 'Finished', field: 'Field 3', accent: 'slate' },
]

const competitions = [
  { name: 'Euro Hockey League', type: 'International', teams: 24, matches: 48, status: 'In progress', color: 'purple' },
  { name: 'Hoofdklasse Men', type: 'National league', teams: 12, matches: 132, status: 'In progress', color: 'amber' },
  { name: 'EHL Women 2026', type: 'International', teams: 16, matches: 32, status: 'Upcoming', color: 'blue' },
]

export default function Home() {
  const [activeNav, setActiveNav] = useState('Overview')
  const [query, setQuery] = useState('')
  const [mobileOpen, setMobileOpen] = useState(false)
  const filteredMatches = useMemo(() => matches.filter((match) => `${match.home} ${match.away} ${match.field}`.toLowerCase().includes(query.toLowerCase())), [query])

  const nav = [
    { label: 'Overview', icon: LayoutDashboard }, { label: 'Matches', icon: CalendarDays },
    { label: 'Teams', icon: Users }, { label: 'Competitions', icon: Trophy },
    { label: 'Score list', icon: ClipboardList },
  ]

  return (
    <div className="min-h-screen bg-[#08090c] text-[#f1f3f5]">
      <aside className={`fixed inset-y-0 left-0 z-20 flex w-[248px] flex-col border-r border-white/[0.07] bg-[#0c0e12] px-4 py-5 transition-transform lg:translate-x-0 ${mobileOpen ? 'translate-x-0' : '-translate-x-full'}`}>
        <div className="mb-9 flex items-center justify-between px-2">
          <div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl bg-[#d7f26b] text-[#11150c]"><Flag /></div><div><p className="text-[15px] font-semibold tracking-tight">Field<span className="text-[#d7f26b]">Flow</span></p><p className="text-[10px] uppercase tracking-[0.2em] text-white/35">Match operations</p></div></div>
          <button aria-label="Close navigation" className="lg:hidden" onClick={() => setMobileOpen(false)}><X /></button>
        </div>
        <p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-white/30">Workspace</p>
        <nav className="flex flex-col gap-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => setActiveNav(label)} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm transition ${activeNav === label ? 'bg-[#d7f26b]/12 text-[#d7f26b]' : 'text-white/55 hover:bg-white/[0.05] hover:text-white'}`}><Icon className="size-[17px]" />{label}{label === 'Matches' && <span className="ml-auto rounded-full bg-[#d7f26b] px-1.5 py-0.5 text-[10px] font-bold text-[#15180e]">12</span>}</button>)}</nav>
        <div className="mt-8"><p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-white/30">Manage</p><nav className="flex flex-col gap-1"><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-white/55 hover:bg-white/[0.05] hover:text-white"><FileText className="size-[17px]" />Reports</button><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-white/55 hover:bg-white/[0.05] hover:text-white"><Settings className="size-[17px]" />Settings</button><button className="flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm text-white/55 hover:bg-white/[0.05] hover:text-white"><CircleHelp className="size-[17px]" />Help center</button></nav></div>
        <div className="mt-auto rounded-xl border border-white/[0.07] bg-white/[0.025] p-3"><div className="mb-3 flex items-center gap-2"><div className="grid size-8 place-items-center rounded-full bg-[#2b3541] text-xs font-semibold">AM</div><div className="min-w-0"><p className="truncate text-xs font-medium">Alex Morgan</p><p className="text-[10px] text-white/40">Technical delegate</p></div><ChevronDown className="ml-auto size-3.5 text-white/35" /></div><button className="flex w-full items-center gap-2 border-t border-white/[0.07] pt-3 text-xs text-white/40 hover:text-white"><LogOut className="size-3.5" />Sign out</button></div>
      </aside>
      {mobileOpen && <button className="fixed inset-0 z-10 bg-black/60 lg:hidden" aria-label="Close navigation overlay" onClick={() => setMobileOpen(false)} />}
      <main className="lg:pl-[248px]">
        <header className="flex h-[72px] items-center justify-between border-b border-white/[0.07] px-5 sm:px-8"><div className="flex items-center gap-3"><button className="lg:hidden" aria-label="Open navigation" onClick={() => setMobileOpen(true)}><Menu /></button><div className="hidden items-center gap-2 text-sm text-white/35 sm:flex"><Command className="size-4" /> <span>Monday, 14 September 2026</span></div><div className="sm:hidden text-sm font-medium">Overview</div></div><div className="flex items-center gap-2 sm:gap-5"><button className="relative rounded-lg p-2 text-white/55 hover:bg-white/[0.05] hover:text-white" aria-label="Notifications"><Bell className="size-[18px]" /><span className="absolute right-1.5 top-1.5 size-1.5 rounded-full bg-[#d7f26b]" /></button><div className="hidden h-5 w-px bg-white/10 sm:block" /><button className="flex items-center gap-2 rounded-lg p-1.5 text-sm hover:bg-white/[0.05]"><div className="grid size-7 place-items-center rounded-full bg-[#c6d7d4] text-[10px] font-bold text-[#19201f]">AM</div><span className="hidden text-white/70 sm:block">Alex Morgan</span><ChevronDown className="hidden size-3.5 text-white/40 sm:block" /></button></div></header>
        <div className="mx-auto max-w-[1420px] px-5 py-7 sm:px-8 lg:px-10 lg:py-9"><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="mb-2 flex items-center gap-2 text-xs font-medium text-[#d7f26b]"><span className="size-1.5 rounded-full bg-[#d7f26b]" />Live workspace</p><h1 className="text-3xl font-semibold tracking-[-0.03em] sm:text-[34px]">Good morning, Alex</h1><p className="mt-2 text-sm text-white/45">Here&apos;s what&apos;s happening across your hockey operations.</p></div><div className="relative w-full sm:w-[260px]"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-white/35" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search matches, teams..." className="h-10 w-full rounded-lg border border-white/10 bg-white/[0.035] pl-9 pr-3 text-xs outline-none transition placeholder:text-white/30 focus:border-[#d7f26b]/50" /></div></div>
          <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Today&apos;s matches" value="12" detail="3 live now" icon={CalendarDays} tone="lime" /><Stat label="Active competitions" value="08" detail="2 starting soon" icon={Trophy} tone="purple" /><Stat label="Registered teams" value="184" detail="+12 this month" icon={Users} tone="blue" /><Stat label="Pending actions" value="06" detail="Requires attention" icon={Zap} tone="amber" /></section>
          <div className="mt-6 grid gap-6 xl:grid-cols-[1.45fr_1fr]"><section className="rounded-xl border border-white/[0.07] bg-[#0d1015]"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div><h2 className="text-sm font-semibold">Today&apos;s matches</h2><p className="mt-1 text-xs text-white/35">Monday, 14 September · All fields</p></div><button className="flex items-center gap-2 rounded-md border border-white/10 px-2.5 py-1.5 text-xs text-white/55 hover:text-white"><SlidersHorizontal className="size-3.5" />Filter</button></div><div className="divide-y divide-white/[0.055]">{filteredMatches.map((match) => <MatchRow key={`${match.time}-${match.home}`} match={match} />)}{!filteredMatches.length && <p className="p-6 text-sm text-white/40">No matches found.</p>}</div><div className="border-t border-white/[0.07] px-5 py-3"><button className="text-xs font-medium text-[#d7f26b] hover:underline">View all matches <span aria-hidden="true">→</span></button></div></section>
            <section className="rounded-xl border border-white/[0.07] bg-[#0d1015]"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div><h2 className="text-sm font-semibold">Active competitions</h2><p className="mt-1 text-xs text-white/35">Your competition overview</p></div><button className="text-xs text-white/45 hover:text-white">View all</button></div><div className="flex flex-col divide-y divide-white/[0.055]">{competitions.map((competition) => <Competition key={competition.name} data={competition} />)}</div><div className="border-t border-white/[0.07] px-5 py-3"><button className="text-xs font-medium text-[#d7f26b] hover:underline">Manage competitions <span aria-hidden="true">→</span></button></div></section></div>
          <section className="mt-6 grid gap-6 lg:grid-cols-[1fr_1fr] xl:grid-cols-[1.1fr_0.9fr]"><div className="rounded-xl border border-white/[0.07] bg-[#0d1015] p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-sm font-semibold">Your role & access</h2><p className="mt-1 text-xs text-white/35">Permissions for this workspace</p></div><ShieldCheck className="size-5 text-[#d7f26b]" /></div><div className="flex items-center gap-3 rounded-lg bg-[#d7f26b]/[0.08] p-3"><div className="grid size-10 place-items-center rounded-full bg-[#c6d7d4] text-xs font-bold text-[#19201f]">AM</div><div><p className="text-sm font-medium">Technical delegate</p><p className="text-xs text-white/40">Full competition access</p></div><span className="ml-auto rounded-full border border-[#d7f26b]/20 px-2 py-1 text-[10px] text-[#d7f26b]">Active</span></div><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Access label="Matches" value="Edit" /><Access label="Teams" value="Manage" /><Access label="Reports" value="View" /></div></div><div className="rounded-xl border border-[#d7f26b]/15 bg-[#d7f26b]/[0.055] p-5"><div className="mb-5 flex items-start justify-between"><div><p className="mb-2 inline-flex items-center gap-1.5 rounded-full bg-[#d7f26b]/15 px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-[#d7f26b]"><Flag className="size-3" /> Quick action</p><h2 className="mt-1 text-lg font-semibold tracking-tight">Need to report a result?</h2><p className="mt-1 max-w-[300px] text-xs leading-5 text-white/45">Submit a final score or update match officials in a few steps.</p></div><ClipboardList className="size-5 text-[#d7f26b]" /></div><button className="rounded-lg bg-[#d7f26b] px-3 py-2 text-xs font-semibold text-[#14180d] hover:bg-[#e2f88b]">Open score list</button></div></section>
        </div>
      </main>
    </div>
  )
}

function Stat({ label, value, detail, icon: Icon, tone }: { label: string; value: string; detail: string; icon: React.ElementType; tone: string }) { return <div className="rounded-xl border border-white/[0.07] bg-[#0d1015] p-4"><div className="mb-5 flex items-start justify-between"><p className="text-xs text-white/45">{label}</p><span className={`grid size-7 place-items-center rounded-lg ${tone === 'lime' ? 'bg-[#d7f26b]/10 text-[#d7f26b]' : tone === 'purple' ? 'bg-[#a98cff]/10 text-[#a98cff]' : tone === 'blue' ? 'bg-[#82b6ff]/10 text-[#82b6ff]' : 'bg-[#ffc478]/10 text-[#ffc478]'}`}><Icon className="size-3.5" /></span></div><div className="flex items-end justify-between"><p className="text-2xl font-semibold tracking-tight">{value}</p><p className="text-[11px] text-white/35">{detail}</p></div></div> }
function MatchRow({ match }: { match: typeof matches[number] }) { return <div className="flex items-center gap-3 px-5 py-4"><div className="w-[42px] text-xs font-medium text-white/65">{match.time}</div><div className={`size-1.5 rounded-full ${match.status === 'Live' ? 'bg-[#d7f26b] shadow-[0_0_8px_#d7f26b]' : match.status === 'Finished' ? 'bg-white/25' : 'bg-[#82b6ff]'}`} /><div className="min-w-0 flex-1"><div className="flex items-center gap-2 text-xs"><span className="truncate font-medium">{match.home}</span><span className="text-white/25">vs</span><span className="truncate text-white/65">{match.away}</span></div><p className="mt-1 text-[10px] text-white/30">{match.field}</p></div><div className="flex items-center gap-2 text-sm font-semibold"><span>{match.homeScore}</span><span className="text-white/20">:</span><span>{match.awayScore}</span></div><span className={`hidden w-[62px] rounded-full px-2 py-1 text-center text-[10px] sm:block ${match.status === 'Live' ? 'bg-[#d7f26b]/10 text-[#d7f26b]' : match.status === 'Finished' ? 'bg-white/[0.06] text-white/40' : 'bg-[#82b6ff]/10 text-[#82b6ff]'}`}>{match.status}</span></div> }
function Competition({ data }: { data: typeof competitions[number] }) { return <div className="flex items-center gap-3 px-5 py-4"><div className={`grid size-9 place-items-center rounded-lg ${data.color === 'purple' ? 'bg-[#a98cff]/10 text-[#a98cff]' : data.color === 'amber' ? 'bg-[#ffc478]/10 text-[#ffc478]' : 'bg-[#82b6ff]/10 text-[#82b6ff]'}`}><Trophy className="size-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{data.name}</p><p className="mt-1 text-[10px] text-white/35">{data.type} · {data.teams} teams · {data.matches} matches</p></div><span className="hidden rounded-full bg-white/[0.06] px-2 py-1 text-[10px] text-white/50 sm:block">{data.status}</span></div> }
function Access({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border border-white/[0.06] bg-white/[0.025] px-2 py-2.5"><p className="text-[10px] text-white/35">{label}</p><p className="mt-1 text-xs font-medium text-white/75">{value}</p></div> }
